name: Pre-Builds dev versions
on:
  push:
    branches: [ dev ]
concurrency: sba_v157
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: 17
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Read value from Properties-file
        id: read_property
        uses: Reedyuk/read-properties@v1.0.4
        with:
          path: './gradle.properties'
          property: 'SBA_VERSION'
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
            echo "{branch}=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_STATE
            echo "{sha_short}=$(git rev-parse --short HEAD)" >> $GITHUB_STATE
      - name: Build with Gradle
        run: ./gradlew
        env:
          OPTIMIZE_FOR_CI_CD: "1"
          BUILD_NUMBER: ${{ github.run_id }}
          GITHUB_ACTIONS_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          GITHUB_COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "LICENSE,plugin/build/libs/*.jar"
          tag: ${{ steps.read_property.outputs.value }}
          allowUpdates: true
          prerelease: true
